package no.uio.inf1010.oblig1.oddmunds;

public class Oblig {

	/**s
	 * @param args
	 */
	public static void main(String[] args) {
		PersonList pl = new PersonList();
		
		fill(pl);

		int i = 0;
		Person p = pl.getFirst();
		while(i==0){
		    System.out.println(p.getName() + ", " + p.getUsername());
		    if(p.hasNext()){
		        p = p.getNext();
		    } else {
		        i = 1;
		        System.out.println("--\n-- Dett var dett.");
		    }
		}
		
	}

    private static void fill(PersonList pl) {
        pl.add(new Person("mrt","Kasra"));
		pl.add(new Person("avinnogg","Anders"));
		pl.add(new Person("prebenno","Preben Nenseth"));
		pl.add(new Person("kseielst","Kirsten Marie"));
		pl.add(new Person("tanxn","Xuan Tan"));
		pl.add(new Person("sigurdsa","Sigurd"));
		pl.add(new Person("huij","Hui"));
		pl.add(new Person("anderbn","Anders Blom"));
		pl.add(new Person("omelgsto","Øyvind"));
		pl.add(new Person("joakibj","Joakim"));
		pl.add(new Person("richar","Richard"));
		pl.add(new Person("linnaad","Linn Kristin"));
		pl.add(new Person("hennikar","Henni"));
		pl.add(new Person("haavarte","Håvard"));
		pl.add(new Person("rubendw","Ruben"));
		pl.add(new Person("dingh","Ding"));
		pl.add(new Person("nikitam","Nikita"));
		pl.add(new Person("huyt","Huy Quang"));
		pl.add(new Person("chunyuyc","Chun-Yu"));
		pl.add(new Person("kabeern","Kabeer"));
		pl.add(new Person("ivicam","Ivica"));
		pl.add(new Person("jorgebfr","Jørgen Bentseng"));
		pl.add(new Person("torbjsk","Torbjørn Skyberg"));
		pl.add(new Person("kenneka","Kenneth"));
		pl.add(new Person("geirrn","Geir Roar"));
		pl.add(new Person("mariebf","Marie Beate"));
		pl.add(new Person("akbarf","Shahab Faghihi"));
		pl.add(new Person("rafaellm","Rafael Lukas"));
		pl.add(new Person("ummairt","Ummair"));
		pl.add(new Person("liweiw","Liwei"));
		pl.add(new Person("suhasgj","Suhas Govind"));
		pl.add(new Person("girmayzg","Girmay Zerom"));
		pl.add(new Person("mettelol","Mette"));
		pl.add(new Person("puilingt","Puiling"));
		pl.add(new Person("prebeo","Preben Nenseth"));
		pl.add(new Person("gauravch","Gaurav"));
		pl.add(new Person("wwalmnes","W. Francis Daraman"));
		pl.add(new Person("kristelf","Kristina Heyerdahl"));
		pl.add(new Person("mshaugla","Martin Severin "));
		pl.add(new Person("svensai","Sven"));
		pl.add(new Person("matshr","Mats Holm"));
		pl.add(new Person("wardaha","Warda"));
		pl.add(new Person("hilia","Hili"));
		pl.add(new Person("jmopsahl","Jan Magnus Granberg"));
		pl.add(new Person("rebekkjm","Rebekka Johanne"));
		pl.add(new Person("stianaki","Stian Aune"));
		pl.add(new Person("espenala","Espen-Alexis"));
		pl.add(new Person("amjansbe","Anne Marte Ihler"));
		pl.add(new Person("navdees","Navdeep"));
		pl.add(new Person("fredva","Fredrik"));
		pl.add(new Person("dkkriste","David Kai Christen"));
		pl.add(new Person("ojalass","Ojala Saghir"));
		pl.add(new Person("robinmy","Robin"));
		pl.add(new Person("sohailmm","Sohail Musa"));
		pl.add(new Person("atifrm","Atif Rashid"));
		pl.add(new Person("kristwil","Kristian"));
		pl.add(new Person("illias","Illia"));
		pl.add(new Person("eivinsax","Eivind"));
		pl.add(new Person("abdulwm","Abdul Wahab"));
		pl.add(new Person("reidarab","Reidar Andre"));
		pl.add(new Person("tinajk","Tina Jeanette"));
		pl.add(new Person("kkho","Khiem-Kim Xuan"));
		pl.add(new Person("junemto","June Marie"));
		pl.add(new Person("dmitrijv","Dmitrij"));
		pl.add(new Person("baardha","Baard"));
		pl.add(new Person("toresj","Tore Sivert Johnsen"));
		pl.add(new Person("ngatl","Nga Tuyet Thi"));
		pl.add(new Person("magnel","Magne Andre"));
		pl.add(new Person("elsagt","Elsa Gabrielle"));
		pl.add(new Person("anderv","Anders"));
		pl.add(new Person("josteili","Jostein"));
		pl.add(new Person("magnusri","Magnus"));
		pl.add(new Person("olesb","Ole Stian"));
		pl.add(new Person("trondni","Trond Anders"));
		pl.add(new Person("erikwb","Erik Wilhelm"));
		pl.add(new Person("behrozm","Behroz"));
		pl.add(new Person("thomaark","Thomas"));
		pl.add(new Person("kyrreg","Kyrre Matias"));
		pl.add(new Person("torbjh","Torbjørn Bull"));
		pl.add(new Person("helgehf","Helge Heyerdahl"));
		pl.add(new Person("erikberg","Erik"));
		pl.add(new Person("sasam","Sasa"));
		pl.add(new Person("ajmolvae","Arnold John Ngugi"));
		pl.add(new Person("henrikhe","Henrik Strømme"));
		pl.add(new Person("kjetilge","Kjetil"));
		pl.add(new Person("erlendp","Erlend"));
		pl.add(new Person("ingeml","Inger Margrethe"));
		pl.add(new Person("hennihor","Henning"));
		pl.add(new Person("erlendvr","Erlend Vihovde"));
		pl.add(new Person("chrismaa","Christine"));
		pl.add(new Person("dishankr","Dishanker"));
		pl.add(new Person("lubnar","Lubna"));
		pl.add(new Person("perats","Per Anders"));
		pl.add(new Person("moayadi","Moayad"));
		pl.add(new Person("kristoth","Kristoffer"));
		pl.add(new Person("hogenhaa","Aksel"));
		pl.add(new Person("frodevw","Frode Vegard"));
		pl.add(new Person("davidjo","David Jørgensen"));
		pl.add(new Person("raouln","Raoul"));
		pl.add(new Person("arnehs","Arne Haugum"));
		pl.add(new Person("gurilu","Guri"));
		pl.add(new Person("bernob","Bernt Øivind"));
		pl.add(new Person("eivinhb","Eivind Haukås"));
		pl.add(new Person("olegf","Oleg Petrovich"));
		pl.add(new Person("ramunek","Ramune"));
		pl.add(new Person("irinaia","Irina Igorevna"));
		pl.add(new Person("chrinr","Christopher Neumann"));
		pl.add(new Person("andrss","Andres Sørensen"));
		pl.add(new Person("jonad","Jon Andre"));
		pl.add(new Person("marold","Mari Sveum"));
		pl.add(new Person("erikjsi","Erik Jonathan"));
		pl.add(new Person("morbergm","Morten"));
		pl.add(new Person("carolsku","Caroline"));
		pl.add(new Person("haakno","Håkon"));
		pl.add(new Person("ramting","Ramtin"));
		pl.add(new Person("narink","Narin"));
		pl.add(new Person("philipcs","Philip Christian"));
		pl.add(new Person("helenens","Helene Norheim"));
		pl.add(new Person("madeleii","Madeleine G"));
		pl.add(new Person("magnhaan","Magnus Helland"));
		pl.add(new Person("chbr","Christian"));
		pl.add(new Person("matshau","Mats"));
		pl.add(new Person("robertko","Robert"));
		pl.add(new Person("stianval","Stian"));
		pl.add(new Person("peterbb","Peter Brottveit"));
		pl.add(new Person("najiak","Naji Ahmad"));
		pl.add(new Person("oleckv","Ole Christian"));
		pl.add(new Person("pfferrer","Pierre Francois Jean"));
		pl.add(new Person("frodetbj","Frode Tobias"));
		pl.add(new Person("helesa","Helene"));
		pl.add(new Person("martsv","Marte"));
		pl.add(new Person("marienh","Marie Nathalie"));
		pl.add(new Person("haavarot","Håvard Mikkelsen"));
		pl.add(new Person("runarfu","Runar"));
		pl.add(new Person("michaekg","Michael K"));
		pl.add(new Person("mariuten","Marius"));
		pl.add(new Person("simenheg","Simen"));
		pl.add(new Person("thomahg","Thomas Hoel"));
		pl.add(new Person("eirikds","Eirik Djupvik"));
		pl.add(new Person("einarnot","Einar"));
		pl.add(new Person("bendikwa","Bendik Wang"));
		pl.add(new Person("erim","Erik"));
		pl.add(new Person("torjusha","Torjus"));
		pl.add(new Person("fredrll","Fredrik Lyder"));
		pl.add(new Person("borissi","Boris"));
		pl.add(new Person("kennetsa","Kenneth Solbø"));
		pl.add(new Person("simenbu","Simen"));
		pl.add(new Person("maximh","Maxim"));
		pl.add(new Person("djamela","Djamel"));
		pl.add(new Person("konstaaz","Konstantin Aleksandrovich"));
		pl.add(new Person("nawrozk","Nawroz"));
		pl.add(new Person("jingt","Jing"));
		pl.add(new Person("fredrvaa","Fredrik"));
		pl.add(new Person("mariasfo","Victoria"));
		pl.add(new Person("gunnaaur","Gunnar"));
		pl.add(new Person("eivinded","Eivind Evenstad"));
		pl.add(new Person("mikkeln","Mikkel"));
		pl.add(new Person("andrsha","Andreas Stusvik"));
		pl.add(new Person("alexpe","Alex"));
		pl.add(new Person("mohammkk","Mohammad Khidash"));
		pl.add(new Person("espenoh","Espen O"));
		pl.add(new Person("brynjagr","Brynjar Grønhaug"));
		pl.add(new Person("markussd","Markus Sortland"));
		pl.add(new Person("arvee","Arve"));
		pl.add(new Person("arildre","Arild"));
		pl.add(new Person("ronvu","Ron Vidar"));
		pl.add(new Person("erlendax","Erlend"));
		pl.add(new Person("patricd","Patrick"));
		pl.add(new Person("zinair","Zina Ida"));
		pl.add(new Person("jonasbl","Jonas Bøhn"));
		pl.add(new Person("sofieseb","Sofie"));
		pl.add(new Person("magnudev","Magnus"));
		pl.add(new Person("eivindpr","Eivind"));
		pl.add(new Person("ingrisw","Ingrid Semb"));
		pl.add(new Person("anderkry","Anders"));
		pl.add(new Person("steinbs","Stein By"));
		pl.add(new Person("olavaand","Olav Andre"));
		pl.add(new Person("kyrrehe","Kyrre Havik"));
		pl.add(new Person("samik","Sami"));
		pl.add(new Person("rafunke","Richard Alexander"));
		pl.add(new Person("torgebo","Torgeir"));
		pl.add(new Person("farahkh","Farah"));
		pl.add(new Person("pmbraath","Paal Mikkel S"));
		pl.add(new Person("eivinbar","Eivind"));
		pl.add(new Person("ljhetlan","Lars Johannes Fjeldså"));
		pl.add(new Person("sigvef","Sigve"));
		pl.add(new Person("makirip","Hans-Olav Maki"));
		pl.add(new Person("fredreng","Fredrik"));
		pl.add(new Person("nghiepv","Nghiep Van"));
		pl.add(new Person("williarm","William R"));
		pl.add(new Person("tomasjoh","Tomas"));
		pl.add(new Person("tatyanac","Tatyana"));
		pl.add(new Person("beritlar","Berit"));
		pl.add(new Person("bwkriste","Benjamin Werner Bych"));
		pl.add(new Person("oystsand","Øystein"));
		pl.add(new Person("krth","Kristian"));
		pl.add(new Person("fridtjha","Fridtjof"));
		pl.add(new Person("mortenkw","Morten Krokan"));
		pl.add(new Person("jorgenks","Jørgen Krog"));
		pl.add(new Person("bjornagh","Bjørnar Grindhaug"));
		pl.add(new Person("miriakh","Miriam Kirstine"));
		pl.add(new Person("magnujoh","Magnus"));
		pl.add(new Person("oddmm","Odd Magnus"));
		pl.add(new Person("rvfjellb","Rune Vegard Skullerud"));
		pl.add(new Person("mariaroi","Marianne"));
		pl.add(new Person("effata","Effat"));
		pl.add(new Person("jamesdt","James David"));
		pl.add(new Person("dagolo","Dag Øyvind"));
		pl.add(new Person("johnaby","John Alexander"));
		pl.add(new Person("marishu","Mari Sønsteby"));
		pl.add(new Person("kentol","Kent"));
		pl.add(new Person("sverrhol","Sverre"));
		pl.add(new Person("henninbw","Henning Bauer"));
		pl.add(new Person("jacquelo","Jacqueline Osei"));
		pl.add(new Person("espegri","Espen"));
		pl.add(new Person("marstorh","Marius"));
		pl.add(new Person("hennikl","Henning"));
		pl.add(new Person("andrefos","Andreas"));
		pl.add(new Person("asgeirom","Asgeir Oldernes"));
		pl.add(new Person("alinach","Alina"));
		pl.add(new Person("magnutr","Magnus"));
		pl.add(new Person("snorrewb","Snorre William"));
		pl.add(new Person("baomn","Bao Marianna"));
		pl.add(new Person("benjamba","Benjamin Brunvoll"));
		pl.add(new Person("alexso","Alex"));
		pl.add(new Person("gryseg","Gry Siri"));
		pl.add(new Person("arsenc","Arsen"));
		pl.add(new Person("bentaf","Bent Anders"));
		pl.add(new Person("sarahbs","Sarah Beate"));
		pl.add(new Person("linnkbr","Linn Kristine"));
		pl.add(new Person("andehag","Anders"));
		pl.add(new Person("patrisk","Patrick Bauge"));
		pl.add(new Person("krishols","Kristine Bøhler"));
		pl.add(new Person("knutrok","Knut"));
		pl.add(new Person("kristony","Kristoffer"));
		pl.add(new Person("jennyli","Jenny"));
		pl.add(new Person("jonfg","Jon Ferdinand"));
		pl.add(new Person("toreon","Tore Olav"));
		pl.add(new Person("sindrepu","Sindre"));
		pl.add(new Person("ragnarsm","Ragnar"));
		pl.add(new Person("fredrme","Fredrik"));
		pl.add(new Person("fredriwa","Fredrik"));
		pl.add(new Person("vegardko","Vegard"));
		pl.add(new Person("thorhw","Thor Henning"));
		pl.add(new Person("marstorh","Marius"));
		pl.add(new Person("hermang","Herman"));
		pl.add(new Person("haakobja","Håkon Botnmark"));
		pl.add(new Person("steinshe","Steinar Sørli"));
		pl.add(new Person("jondr","Jon Dahl"));
		pl.add(new Person("semird","Semir"));
		pl.add(new Person("torbjpl","Torbjørn P"));
		pl.add(new Person("kinevl","Kine Veronica"));
		pl.add(new Person("jarandkh","Jarand Kiste"));
		pl.add(new Person("odarn","Oda Rønholt"));
		pl.add(new Person("oleseg","Ole"));
		pl.add(new Person("oystebjo","Øystein"));
		pl.add(new Person("sofiacl","Sofia"));
		pl.add(new Person("ophatm","Ophat"));
		pl.add(new Person("fredrhaa","Fredrik"));
		pl.add(new Person("martigla","Martin Gullien"));
		pl.add(new Person("mattiahj","Mattias Håheim"));
		pl.add(new Person("haavanes","Håvard"));
		pl.add(new Person("scfure","Silje Christine R"));
		pl.add(new Person("mohammrg","Mohammad Reza"));
		pl.add(new Person("mortensi","Morten Wåsjø"));
		pl.add(new Person("camilve","Camilla"));
		pl.add(new Person("sindrenm","Sindre Nordberg"));
		pl.add(new Person("petteaar","Petter"));
		pl.add(new Person("marifor","Maria"));
		pl.add(new Person("marstorh","Marius"));
		pl.add(new Person("karenwf","Karen Wanvik"));
		pl.add(new Person("larsjeng","Lars Jansøn"));
		pl.add(new Person("fredrins","Fredrik Notevarp"));
		pl.add(new Person("vegarang","Vegard"));
		pl.add(new Person("jorundal","Jørund"));
		pl.add(new Person("endrebs","Endre Bunes"));
		pl.add(new Person("torees","Tore Mikal"));
		pl.add(new Person("olavpo","Olav"));
		pl.add(new Person("marinan","Marina"));
		pl.add(new Person("sirins","Siri Nærland"));
		pl.add(new Person("ahbfinst","Ann-Charlotte Birgitta"));
		pl.add(new Person("anishr","Anish"));
		pl.add(new Person("axelbh","Axel Butler"));
		pl.add(new Person("jenserin","Jens Erik"));
		pl.add(new Person("zhiyansa","Zhiyan"));
		pl.add(new Person("emanuel","Emanuele"));
		pl.add(new Person("jorgeren","Jørgen Vold"));
		pl.add(new Person("maartena","Arthur"));
		pl.add(new Person("hatt","Thanh Ha"));
		pl.add(new Person("vivihn","Vivi Hoang"));
		pl.add(new Person("jorgevi","Jørgen"));
		pl.add(new Person("daniero","Daniel"));
		pl.add(new Person("eirikrl","Eirik Røbech"));
		pl.add(new Person("dinhut","Dinh Uy"));
		pl.add(new Person("tommhald","Tommy"));
		pl.add(new Person("ilirn","Ilir"));
		pl.add(new Person("marstorh","Marius"));
		pl.add(new Person("rizwanaa","Rizwan Ali"));
		pl.add(new Person("fredriti","Fredrik"));
		pl.add(new Person("olearos","Ole Andreas"));
		pl.add(new Person("thomamha","Thomas Misund"));
		pl.add(new Person("pederbe","Peder"));
		pl.add(new Person("sigbjogs","Sigbjørn Gulløv"));
		pl.add(new Person("olekto","Ole Kristian"));
		pl.add(new Person("lenacar","Lena Christine Lund"));
		pl.add(new Person("oddmunds","Oddmund"));
		pl.add(new Person("javalla","Joakim"));
		pl.add(new Person("andrebog","Andreas"));
		pl.add(new Person("jannro","Jan Nyquvist"));
		pl.add(new Person("erlenkr","Erlend"));
		pl.add(new Person("shabnapi","Shabnam"));
		pl.add(new Person("aleksase","Aleksander"));
		pl.add(new Person("mudasirs","Mudasir Esmael"));
		pl.add(new Person("igorkol","Igor"));
		pl.add(new Person("bahonurn","Bahonur"));
		pl.add(new Person("princej","Prince"));
		pl.add(new Person("evaghi","Eva Gamlesæter"));
		pl.add(new Person("paihler","Per Anton Fagerholt"));
		pl.add(new Person("dansk","Dan Scheslien"));
		pl.add(new Person("admicha","Abel Gebre Michael"));
		pl.add(new Person("tommysae","Tommy"));
		pl.add(new Person("atvaerne","Anh Tuyet Thi"));
		pl.add(new Person("migrana","Menua"));
		pl.add(new Person("sasoria","Sergio Alberto Arevalo"));
		pl.add(new Person("simenren","Simen"));
		pl.add(new Person("runeyt","Rune Y."));
		pl.add(new Person("bartoszp","Bartosz"));
		pl.add(new Person("jmjohann","Jørgen Mundgjel Fjeld"));
		pl.add(new Person("fabiantf","Fabian Tytingvåg"));
		pl.add(new Person("oyvstenl","Øyvind"));
		pl.add(new Person("kritr","Kristian"));
		pl.add(new Person("torgeirl","Torgeir Lyche"));
		pl.add(new Person("tmtaklo","Tore Magnus Arnesen"));
		pl.add(new Person("espenmei","Espen Moen"));
		pl.add(new Person("bsalhell","Basil Seifadd(new Personin Hussain Al"));
		pl.add(new Person("henrihel","Henrik"));
		pl.add(new Person("lukaszjm","Lukasz Jan"));
		pl.add(new Person("eirigro","Eirik"));
		pl.add(new Person("khalidab","Khalid Mussanur"));
		pl.add(new Person("oleksank","Oleksandra"));
		pl.add(new Person("karimac","Karima"));
		pl.add(new Person("bahonurn","Bahonur"));
		pl.add(new Person("mikalm","Mikal"));
		pl.add(new Person("jmring","Janusz Mieczyslaw"));
		pl.add(new Person("haakonoo","Håkon Olav"));
		pl.add(new Person("mariubac","Marius"));
		pl.add(new Person("masjurse","Magnus"));
		pl.add(new Person("andrberg","Andreas"));
		pl.add(new Person("anderrb","Anders Ramsvik"));
		pl.add(new Person("menalta","Menal Talal"));
		pl.add(new Person("cecilyyz","Cecily Yan"));
		pl.add(new Person("benct","Ben Christopher"));
		pl.add(new Person("oyvinin","Øyvind"));
		pl.add(new Person("moniksk","Monika Sperstad"));
		pl.add(new Person("ejjohans","Erlend Johan Strømhaug"));
		pl.add(new Person("thomapor","Thomas"));
		pl.add(new Person("tahiray","Tahira"));
		pl.add(new Person("josek","Jose Louis"));
		pl.add(new Person("stianf","Stian Kjetil"));
		pl.add(new Person("bendiko","Bendik Rønning"));
		pl.add(new Person("bmmender","Bedeho"));
		pl.add(new Person("espeak","Espen Angell"));
		pl.add(new Person("richar","Richard"));
		pl.add(new Person("jpaasen","Jon"));
		pl.add(new Person("daghf","Dag Haavi"));
		pl.add(new Person("larsstor","Lars"));
		pl.add(new Person("fredva","Fredrik"));
		pl.add(new Person("steing","Stein"));
		pl.add(new Person("michael","Stein Michael"));
		pl.add(new Person("stm","Stein Michael"));
    }

}
